# This is the default config.yml for SimpleBroadcast.
# Plugin made by KingDome24.
# If you need help visit http://www.SimpleBroadcast.net
# Please be sure that all your messages are inside of single quotes!
# The update checking requires an Internet connection.
# PluginMetrics also requires an Internet connection.

enabled: true

delay: 60 # time in seconds

prefix:
  enabled: true
  prefix: '&d[Broadcast]&7'
  
suffix:
  enabled: false
  suffix: '&d[v1.8.1]'
  
pluginmetrics: true

checkforupdates: true

randomizemessages: false

requiresonlineplayers: false

sendmessagestoconsole: false

messages:
- 'Thank you for using SimpleBroadcast!'
- 'Plugin by &oKingDome24.'
- 'If you have questions please visit the BukkitDev page!'
- 'You do not like to edit the config manually? Use "/sb add" or "/sb remove" instead!'