# This is the default config.yml for SimpleBroadcast.
# Plugin made by KingDome24 and yonascode.
# If you need help visit http://www.SimpleBroadcast.net
# Please be sure that all your messages are inside of single quotes!
# The update checking requires an Internet connection.
# PluginMetrics also requires an Internet connection.

enabled: true

delay: 60 # time in seconds

prefix:
  enabled: true
  prefix: '&d[Broadcast]&7'
  
suffix:
  enabled: false
  suffix: '&d[v1.8]'
  
pluginmetrics: true

usepermissions: false

checkforupdates: true

randomizemessages: false

requiresonlineplayers: false

sendmessagestoconsole: false

messages:
  default:
  - 'Thank you for using SimpleBroadcast!'
  - 'Plugin by &oKingDome24 and yonascode.'
  - 'If you have questions please visit the BukkitDev page!'
  - '%laquo%Many new and cool variables are now available%raquo%'
  your.permission.node:
  - 'You can create any permission node you want.'